version: '3'
services:
  db-solva-api:
    image: postgres:16
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: solva-api